#!/usr/bin/env bash
set -o errexit
set -o nounset
# set -o xtrace
set -o pipefail

SCRIPT=$(realpath "$BASH_SOURCE")

API='http://choosealicense.com'
LIST_ITEM='<h3 class="license-family-name"><a>{title:=.,url:=@href}</a></h3>*' 
ITEM_DETAILS='//*[@id="license-text"]' 

LICENSE=$1
if [[ $LICENSE = /licenses/* ]]
then
	xidel -q -e "$ITEM_DETAILS" "$(curl "$API$LICENSE" 2>/dev/null)"
else
	eval "$(xidel -q -e "$LIST_ITEM" "$(curl "$API/licenses/" 2>/dev/null)" --output-format=bash)"
	for ((i=0; i<${#title[@]}; i++))
	do
		echo -e "${title[$i]}\t.!$SCRIPT ${url[$i]}"
	done
fi
