#!/bin/bash -e
SCRIPT="$(realpath "$BASH_SOURCE")"

API='http://choosealicense.com'
LIST_ITEM='<h3 class="license-family-name"><a>{title:=.,url:=@href}</a></h3>*' 
ITEM_DETAILS='//*[@id="license-text"]' 

LICENSE="$1"
if [[ "$LICENSE" = /licenses/* ]]
then
	xidel -q -e "$ITEM_DETAILS" "$API$LICENSE"
else
	eval "$(xidel -q -e "$LIST_ITEM" "$API/licenses/" --output-format=bash)"
	for ((i=0; i<${#title[@]}; i++))
	do
		echo -e "${title[$i]}\tread !$SCRIPT ${url[$i]}"
	done
fi
